--Vim.o.foldcolumn = '1'
--Vim.o.foldlevel = 99 -- Using ufo provider need a large value, feel free to decrease the value
--Vim.o.foldlevelstart = 99
--Vim.o.foldenable = true
--
--Require('ufo').setup()
--
---- Using ufo provider need remap `zR` and `zM`.
--Vim.keymap.set('n', 'zR', require('ufo').openAllFolds)
--Vim.keymap.set('n', 'zM', require('ufo').closeAllFolds)
--
--Local lsp_zero = require('lsp-zero')
--
--Lsp_zero.on_attach(function(client, bufnr)
--	lsp_zero.default_keymaps({buffer = bufnr})
--End)
--
--Lsp_zero.set_server_config({
--	capabilities = {
--		textDocument = {
--			foldingRange = {
--				dynamicRegistration = false,
--				lineFoldingOnly = true
--			}
--		}
--	}
--})
