source-file ~/.config/tmux/scripts/fuzzy_open_sessions.tmux
source-file ~/.config/tmux/scripts/reload_config.tmux
source-file ~/.config/tmux/undercurl.tmux.conf

set -g @plugin 'rose-pine/tmux'

set -g @rose_pine_variant 'main'
set -g @rose_pine_host 'off'
set -g @rose_pine_user 'on'

set -g @rose_pine_status_left_prepend_section ' '

# auto rename windows
set -g allow-rename on
set -g renumber-window on
set -g automatic-rename on
set -g set-titles on

set -g status-justify centre
set -g status-position top

# start index at 1
set -g base-index 1
set -g pane-base-index 1

# enable 256-colors
set -g default-terminal "screen-256color"
set -g focus-events on

# Toggle status bar
bind s set-option -g status

set -g mouse on
set -g set-clipboard on
set -g set-clipboard external

set -g escape-time 0
set -s extended-keys on

# vi mode
set -g status-keys vi
setw -g mode-keys vi

bind -n M-h select-pane -L
bind -n M-l select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Open new windows on current path
bind c new-window -c "#{pane_current_path}"
bind C-c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g @plugin 'tmux-plugins/tpm'

run '~/.config/tmux/plugins/tpm/tpm'
