bind C-s display-popup -E "\
         tmux list-sessions -F '#{session_name}' |\
         sed '/^$/d' |\
         fzf --reverse --header jump-to-session |\
         xargs tmux switch-client -t"

unbind r
unbind C-r

bind r source ~/.config/tmux/tmux.conf \; display-message 'Reloaded tmux config'
bind C-r source ~/.config/tmux/tmux.conf \; display-message 'Reloaded tmux config'

# Enable undercurl
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'

# auto rename windows
set -g renumber-window on
set -g automatic-rename on
set -g set-titles on

# start index at 1
set -g base-index 1
set -g pane-base-index 1

# enable 256-colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g focus-events on

# Toggle status bar
bind s set-option -g status
set -g status-justify left
set -g status-right '%Y-%m-%d %H:%M '
set -g status-style bg=default

set -g mouse on
set -g set-clipboard on
set -g set-clipboard external

set -sg escape-time 0
set -s extended-keys on

# vi mode
set -g status-keys vi
setw -g mode-keys vi

# Open new windows on current path
bind c new-window -c "#{pane_current_path}"
bind C-c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
