require('plugins.fzf-lua')
require('plugins.lspconfig')
require('plugins.tree-sitter')
require('plugins.oil')
require('plugins.themes')
require('plugins.trouble')
require('plugins.flutter-tools')
require('plugins.conform')
