[general]

[colors.primary]
foreground = "#e0def4"
background = "#191724"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[window]
dimensions = { columns = 0, lines = 0 }
padding = { x = 5, y = 0 }
dynamic_padding = true
decorations = "buttonless"
opacity = 1
blur = false
option_as_alt = "Both"

[font]
normal = { family = "monospace" }
size = 14

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
]

[env]
TERM = "screen-256color"
